/**
 * Shared types for the visualizer. These mirror the JSON shapes produced by
 * RPG-Kit (`scripts/rpg_visualize.py`) so a `rpg.json` + `dep_graph.json`
 * generated by either pipeline can be consumed unchanged.
 */

/**
 * A single dep-graph node as stored in `dep_graph.json` under `nodes[id]`.
 * Field names match the vendor's `to_dict()` output verbatim.
 */
export interface RawDepNode {
  type?: string
  module?: string
  name?: string
  rpg_nodes?: string[]
  [key: string]: unknown
}

/** A single dep-graph edge as stored in `dep_graph.json` under `edges`. */
export interface RawDepEdge {
  src: string
  dst: string
  attrs?: { type?: string, [key: string]: unknown }
}

/** The `dep_graph` payload, either embedded or loaded from a sidecar file. */
export interface RawDepGraph {
  repo_dir?: string
  repo_name?: string
  root?: string
  nodes?: Record<string, RawDepNode>
  edges?: RawDepEdge[]
}

/** A single feature/RPG node as stored in `rpg.json` under `nodes`. */
export interface RawFeatNode {
  id: string
  name?: string
  node_type?: string
  level?: number
  meta?: {
    type_name?: string
    path?: string | string[] | null
    description?: string
    [key: string]: unknown
  } | null
  children?: RawFeatNode[]
  [key: string]: unknown
}

/** A single feature/RPG edge as stored in `rpg.json` under `edges`. */
export interface RawFeatEdge {
  src: string
  dst: string
  relation?: string
  [key: string]: unknown
}

/** Tree variant of an RPG (`{ root: { children: [...] } }`). */
export interface NestedRpg {
  root: RawFeatNode
  repo_name?: string
}

/** Flat variant of an RPG (`{ nodes: [...], edges: [...] }`). */
export interface FlatRpg {
  nodes: RawFeatNode[]
  edges?: RawFeatEdge[]
  repo_name?: string
}

/**
 * The top-level structure consumed by the visualizer. Matches the dict
 * returned by `rpg_visualize.py::load_rpg()`.
 */
export interface RpgData {
  repo_name?: string
  root?: RawFeatNode
  nodes?: RawFeatNode[]
  edges?: RawFeatEdge[]
  dep_graph?: RawDepGraph | null
  dep_graph_file?: string | null
  _dep_to_rpg_map?: Record<string, string[]>
  [key: string]: unknown
}

/**
 * Convenience union returned by helpers like `loadRpg()`. Identical to
 * `RpgData`; aliased to keep the surface clear in tests and callers.
 */
export type VisualizeData = RpgData
